
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint front (basic)
        run: |
          test -f dist/assets/css/clean.min.css
          test -f dist/index.html
      - name: Python setup
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install backend deps
        run: pip install -r requirements.txt
      - name: Smoke import
        run: python - <<'PY'\nfrom app.main import app\nprint('OK')\nPY
